// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_RKz6zlJwu-Da_EBoWF2nobtT19NVdQ',
    appId: '1:74487002543:web:4dda469c4e7dca3c9feb5a',
    messagingSenderId: '74487002543',
    projectId: 'etamu-all-in-one',
    authDomain: 'etamu-all-in-one.firebaseapp.com',
    storageBucket: 'etamu-all-in-one.firebasestorage.app',
    measurementId: 'G-7TTNMHYM9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp45D5j-OSEprnxHXvehjSAfCfKh0vKyY',
    appId: '1:74487002543:android:46c974843028453e9feb5a',
    messagingSenderId: '74487002543',
    projectId: 'etamu-all-in-one',
    storageBucket: 'etamu-all-in-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Z_4M4UV-ZWcbJ5OGKzMoVWqun7HllXI',
    appId: '1:74487002543:ios:802e7a9e60bc0f8a9feb5a',
    messagingSenderId: '74487002543',
    projectId: 'etamu-all-in-one',
    storageBucket: 'etamu-all-in-one.firebasestorage.app',
    iosBundleId: 'com.example.etamuAllInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Z_4M4UV-ZWcbJ5OGKzMoVWqun7HllXI',
    appId: '1:74487002543:ios:802e7a9e60bc0f8a9feb5a',
    messagingSenderId: '74487002543',
    projectId: 'etamu-all-in-one',
    storageBucket: 'etamu-all-in-one.firebasestorage.app',
    iosBundleId: 'com.example.etamuAllInOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_RKz6zlJwu-Da_EBoWF2nobtT19NVdQ',
    appId: '1:74487002543:web:83f6eb734feb36b59feb5a',
    messagingSenderId: '74487002543',
    projectId: 'etamu-all-in-one',
    authDomain: 'etamu-all-in-one.firebaseapp.com',
    storageBucket: 'etamu-all-in-one.firebasestorage.app',
    measurementId: 'G-GTD39QKL3G',
  );
}
