name: etamu_all_in_one
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.4.2
  android_intent_plus: ^5.0.2
  url_launcher: ^6.2.4
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  http: ^1.3.0
  icalendar_parser: ^2.0.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  shimmer: ^3.0.0
  html: ^0.15.6
  xml: ^6.5.0
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/etamu_logo.jpg
    - assets/images/login_bg.jpg

  fonts:
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/etamu_logo.jpg"
  adaptive_icon_background: "#002147"
  adaptive_icon_foreground: "assets/images/etamu_logo.jpg"
